spring.application.name=todo_api

# MySQL Database Connection
spring.datasource.url = jdbc:mysql://localhost:3306/todo_db
spring.datasource.username=root
spring.datasource.password=200727mar

# JPA / Hiberbnate orm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080